# Generated by Django 2.2.4 on 2019-10-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0002_auto_20191002_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
