# Generated by Django 2.2.4 on 2019-10-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0003_auto_20191012_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=True, help_text='150x150px', upload_to='media'),
        ),
    ]
