# Generated by Django 2.2.4 on 2019-11-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0006_auto_20191024_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
