# Generated by Django 2.2.4 on 2019-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0007_auto_20191113_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
